import { useState, useEffect } from 'react';

export type Language = 'ru' | 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'ar' | 'pt' | 'hi';

const translations = {
  ru: {
    appName: 'ChimeUp',
    today: 'Сегодня',
    calendar: 'Календарь',
    notes: 'Заметки',
    settings: 'Настройки',
    addTask: 'Добавить задачу',
    taskName: 'Название задачи',
    taskDescription: 'Описание',
    selectDate: 'Дата',
    selectTime: 'Время',
    save: 'Сохранить',
    cancel: 'Отмена',
    edit: 'Редактировать',
    delete: 'Удалить',
    complete: 'Выполнено',
    pending: 'Ожидает',
    tomorrow: 'Завтра',
    timeToComplete: 'Время выполнить!',
    enableNotifications: 'Уведомления',
    noTasks: 'Нет задач',
    createFirst: 'Добавьте свою первую задачу',
    taskCreated: 'Задача создана',
    taskUpdated: 'Задача обновлена',
    taskDeleted: 'Задача удалена',
    taskCompleted: 'Задача выполнена!',
    category: 'Категория',
    repeat: 'Повтор',
    sound: 'Звук',
    listenSound: 'Прослушать',
    snooze5: 'Через 5 мин',
    snooze10: 'Через 10 мин',
    snooze30: 'Через 30 мин',
    snooze60: 'Через 1 час',
    snoozeCustom: 'Повтор через...',
    snoozeCustomPlaceholder: 'Мин.',
    history: 'История',
    clearHistory: 'Очистить историю',
    autoCleanup: 'Автоочистка истории',
    theme: 'Тема',
    themeLight: 'Светлая',
    themeDark: 'Тёмная',
    themeAuto: 'Авто',
    language: 'Язык',
    newNote: 'Новая заметка',
    deleteNote: 'Удалить заметку',
    setReminder: 'Установить напоминание',
    reminderSet: 'Напоминание установлено',
    reminderRemoved: 'Напоминание удалено',
    saveAsDefault: 'Сохранить как основной',
    soundSaved: 'Звук сохранён',
    writeHere: 'Начните писать...',
    medicine: 'Лекарства',
    medicineName: 'Название лекарства',
    medicineTime: 'Время приёма',
    medicineTaken: 'Принято',
    medicineHistory: 'История приёма',
    voiceInput: 'Голосовой ввод',
    noTasksToday: 'На сегодня задач нет',
    enjoyDay: 'Можно отдохнуть! 🎉',
    overdue: 'Просрочено',
    upcoming: 'Предстоящие',
    allTasks: 'Все задачи',
    days7: '7 дней',
    days30: '30 дней',
    days90: '90 дней',
    repeatInterval: 'Интервал (часов)',
    notifEnabled: '✅ Включены',
    notifDisabled: '❌ Выключены',
    notifGranted: '✅ Включены',
    notifDenied: '❌ Отклонены браузером',
    notifUnsupported: '❌ Браузер не поддерживает уведомления',
    historyEmpty: '🎉 Пусто',
    listening: 'Слушаю...',
    aiProcessing: 'AI обрабатывает...',
    voiceConfirmText: 'Проверьте и подтвердите текст:',
    confirm: 'Подтвердить',
    selectDatePicker: 'Выбрать дату',
    customRemindersHint: '📅 Укажите даты и время напоминаний:',
    fillHighlightedFields: '⚠️ Заполните выделенные поля:',
    fieldDate: 'Дата',
    fieldTime: 'Время',
    fieldName: 'Название',
    addReminder: '+ Добавить напоминание',
    reminder: '⏰ Напоминание',
    dismiss: 'Отклонить',
    remindIn10: '⏰ Напомнить через 10 мин',
    remindIn30: '⏰ Напомнить через 30 мин',
    remindIn1h: '⏰ Напомнить через 1 час',
    remindAt: 'Напомнить...',
    chatSaved: '💬 Беседа сохранена',
    aiChatTitle: 'Чат с AI',
    chatHistory: 'История чатов',
    chatPlaceholder: 'Напишите сообщение...',
    saveAll: 'Сохранить всё',
    saveSelected: 'Сохранить выбранное',
    selectMessages: 'Выбрать',
    chatEmpty: 'Начните диалог с AI-помощником',
    newChat: 'Новый чат',
    noHistoryChats: 'Нет сохранённых чатов',
    clearAll: 'Очистить всё',
    clearChat: 'Очистить чат',
    tasks: 'задач',
    speechUnsupported: 'Браузер не поддерживает распознавание речи',
    catHealth: 'Здоровье',
    catWork: 'Работа',
    catPersonal: 'Личное',
    catUrgent: 'Срочно',
    catMedicine: 'Лекарства',
    catBirthday: 'День Рождения',
    repeatNone: 'Без повтора',
    repeatDaily: 'Каждый день',
    repeatMonthly: 'Каждый месяц',
    repeatCustom: 'Произвольный интервал',
    repeatEvery: 'Каждые...',
    repeatEveryHours: 'Каждые (часов)',
    soundBell: 'Колокольчик',
    soundAlarm: 'Будильник',
    soundGentle: 'Мягкий сигнал',
    soundNone: 'Без звука',
    weekMon: 'Пн', weekTue: 'Вт', weekWed: 'Ср', weekThu: 'Чт', weekFri: 'Пт', weekSat: 'Сб', weekSun: 'Вс',
    signIn: 'Войти',
    signUp: 'Регистрация',
    signInGoogle: 'Войти через Google',
    orEmail: 'или по email',
    password: 'Пароль',
    noAccount: 'Нет аккаунта?',
    haveAccount: 'Уже есть аккаунт?',
    authSubtitle: 'Войдите, чтобы синхронизировать задачи',
    authError: 'Ошибка авторизации',
    checkEmail: 'Проверьте почту',
    confirmEmailSent: 'Письмо с подтверждением отправлено',
    logout: 'Выйти',
    installApp: 'Установить приложение',
    installAppDesc: 'Установите ChimeUp на рабочий стол для быстрого доступа',
  },
  en: {
    appName: 'ChimeUp',
    today: 'Today',
    calendar: 'Calendar',
    notes: 'Notes',
    settings: 'Settings',
    addTask: 'Add Task',
    taskName: 'Task name',
    taskDescription: 'Description',
    selectDate: 'Date',
    selectTime: 'Time',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    complete: 'Done',
    pending: 'Pending',
    tomorrow: 'Tomorrow',
    timeToComplete: 'Time to complete!',
    enableNotifications: 'Notifications',
    noTasks: 'No tasks',
    createFirst: 'Add your first task',
    taskCreated: 'Task created',
    taskUpdated: 'Task updated',
    taskDeleted: 'Task deleted',
    taskCompleted: 'Task completed!',
    category: 'Category',
    repeat: 'Repeat',
    sound: 'Sound',
    listenSound: 'Preview',
    snooze5: 'In 5 min',
    snooze10: 'In 10 min',
    snooze30: 'In 30 min',
    snooze60: 'In 1 hour',
    snoozeCustom: 'Snooze in...',
    snoozeCustomPlaceholder: 'Min.',
    history: 'History',
    clearHistory: 'Clear history',
    autoCleanup: 'Auto cleanup',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeAuto: 'Auto',
    language: 'Language',
    newNote: 'New note',
    deleteNote: 'Delete note',
    reminderSet: 'Reminder set',
    reminderRemoved: 'Reminder removed', 
    saveAsDefault: 'Save as default',
    soundSaved: 'Sound saved',
    writeHere: 'Start writing...',
    medicine: 'Medicine',
    medicineName: 'Medicine name',
    medicineTime: 'Intake time',
    medicineTaken: 'Taken',
    medicineHistory: 'Intake history',
    voiceInput: 'Voice input',
    noTasksToday: 'No tasks for today',
    enjoyDay: 'Time to relax! 🎉',
    overdue: 'Overdue',
    upcoming: 'Upcoming',
    allTasks: 'All tasks',
    days7: '7 days',
    days30: '30 days',
    days90: '90 days',
    repeatInterval: 'Interval (hours)',
    notifEnabled: '✅ Enabled',
    notifDisabled: '❌ Disabled',
    notifGranted: '✅ Enabled',
    notifDenied: '❌ Denied by browser',
    notifUnsupported: '❌ Browser does not support notifications',
    historyEmpty: '🎉 Empty',
    listening: 'Listening...',
    aiProcessing: 'AI is processing...',
    voiceConfirmText: 'Check and confirm text:',
    confirm: 'Confirm',
    selectDatePicker: 'Select date',
    customRemindersHint: '📅 Set dates and times for reminders:',
    fillHighlightedFields: '⚠️ Fill in highlighted fields:',
    fieldDate: 'Date',
    fieldTime: 'Time',
    fieldName: 'Name',
    addReminder: '+ Add reminder',
    reminder: '⏰ Reminder',
    dismiss: 'Dismiss',
    remindIn10: '⏰ Remind in 10 min',
    remindIn30: '⏰ Remind in 30 min',
    remindIn1h: '⏰ Remind in 1 hour',
    remindAt: 'Remind at...',
    setReminder: 'Set reminder',
    chatSaved: '💬 Chat saved',
    aiChatTitle: 'AI Chat',
    chatHistory: 'Chat History',
    chatPlaceholder: 'Type a message...',
    saveAll: 'Save all',
    saveSelected: 'Save selected',
    selectMessages: 'Select',
    chatEmpty: 'Start a conversation with AI assistant',
    newChat: 'New chat',
    noHistoryChats: 'No saved chats',
    clearAll: 'Clear all',
    clearChat: 'Clear chat',
    tasks: 'tasks',
    speechUnsupported: 'Browser does not support speech recognition',
    catHealth: 'Health',
    catWork: 'Work',
    catPersonal: 'Personal',
    catUrgent: 'Urgent',
    catMedicine: 'Medicine',
    catBirthday: 'Birthday',
    repeatNone: 'No repeat',
    repeatDaily: 'Every day',
    repeatEvery: 'Every...',
    repeatEveryHours: 'Every (hours)',
    repeatMonthly: 'Every month',
    repeatCustom: 'Custom interval',
    soundBell: 'Bell',
    soundAlarm: 'Alarm',
    soundGentle: 'Gentle',
    soundNone: 'Silent',
    weekMon: 'Mon', weekTue: 'Tue', weekWed: 'Wed', weekThu: 'Thu', weekFri: 'Fri', weekSat: 'Sat', weekSun: 'Sun',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signInGoogle: 'Sign in with Google',
    orEmail: 'or with email',
    password: 'Password',
    noAccount: 'No account?',
    haveAccount: 'Already have an account?',
    authSubtitle: 'Sign in to sync your tasks',
    authError: 'Auth error',
    checkEmail: 'Check your email',
    confirmEmailSent: 'Confirmation email sent',
    logout: 'Log out',
    installApp: 'Install App',
    installAppDesc: 'Install ChimeUp to your desktop for quick access',
  },
  es: {
    appName: 'ChimeUp',
    today: 'Hoy',
    calendar: 'Calendario',
    notes: 'Notas',
    settings: 'Ajustes',
    addTask: 'Añadir tarea',
    taskName: 'Nombre de la tarea',
    taskDescription: 'Descripción',
    selectDate: 'Fecha',
    selectTime: 'Hora',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Eliminar',
    complete: 'Hecho',
    pending: 'Pendiente',
    tomorrow: 'Mañana',
    timeToComplete: '¡Hora de completar!',
    enableNotifications: 'Notificaciones',
    noTasks: 'Sin tareas',
    createFirst: 'Añade tu primera tarea',
    taskCreated: 'Tarea creada',
    taskUpdated: 'Tarea actualizada',
    taskDeleted: 'Tarea eliminada',
    taskCompleted: '¡Tarea completada!',
    category: 'Categoría',
    repeat: 'Repetir',
    sound: 'Sonido',
    listenSound: 'Escuchar',
    snooze5: 'En 5 min',
    snooze10: 'En 10 min',
    snooze30: 'En 30 min',
    snooze60: 'En 1 hora',
    snoozeCustom: 'Repetir en...',
    snoozeCustomPlaceholder: 'Min.',
    history: 'Historial',
    clearHistory: 'Borrar historial',
    autoCleanup: 'Limpieza automática',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Oscuro',
    themeAuto: 'Auto',
    language: 'Idioma',
    newNote: 'Nueva nota',
    deleteNote: 'Eliminar nota',
    writeHere: 'Empieza a escribir...',
    medicine: 'Medicina',
    medicineName: 'Nombre de la medicina',
    medicineTime: 'Hora de toma',
    medicineTaken: 'Tomado',
    medicineHistory: 'Historial de tomas',
    voiceInput: 'Entrada de voz',
    noTasksToday: 'No hay tareas para hoy',
    enjoyDay: '¡A relajarse! 🎉',
    overdue: 'Atrasado',
    upcoming: 'Próximos',
    allTasks: 'Todas las tareas',
    days7: '7 días',
    days30: '30 días',
    days90: '90 días',
    repeatInterval: 'Intervalo (horas)',
    notifEnabled: '✅ Activadas',
    notifDisabled: '❌ Desactivadas',
    notifGranted: '✅ Activadas',
    notifDenied: '❌ Rechazadas por el navegador',
    notifUnsupported: '❌ El navegador no soporta notificaciones',
    historyEmpty: '🎉 Vacío',
    listening: 'Escuchando...',
    aiProcessing: 'AI procesando...',
    voiceConfirmText: 'Revise y confirme el texto:',
    confirm: 'Confirmar',
    selectDatePicker: 'Seleccionar fecha',
    customRemindersHint: '📅 Indique fechas y horas de recordatorios:',
    fillHighlightedFields: '⚠️ Complete los campos resaltados:',
    fieldDate: 'Fecha',
    fieldTime: 'Hora',
    fieldName: 'Nombre',
    addReminder: '+ Añadir recordatorio',
    reminder: '⏰ Recordatorio',
    dismiss: 'Descartar',
    remindIn10: '⏰ Recordar en 10 min',
    remindIn30: '⏰ Recordar en 30 min',
    remindIn1h: '⏰ Recordar en 1 hora',
    remindAt: 'Recordar...',
    setReminder: 'Establecer recordatorio',
    chatSaved: '💬 Chat guardado',
    aiChatTitle: 'Chat con AI',
    chatHistory: 'Historial de chats',
    chatPlaceholder: 'Escriba un mensaje...',
    saveAll: 'Guardar todo',
    saveSelected: 'Guardar selección',
    selectMessages: 'Seleccionar',
    chatEmpty: 'Inicie una conversación con el asistente AI',
    newChat: 'Nuevo chat',
    noHistoryChats: 'No hay chats guardados',
    clearAll: 'Borrar todo',
    clearChat: 'Borrar chat',
    tasks: 'tareas',
    speechUnsupported: 'El navegador no soporta reconocimiento de voz',
    catHealth: 'Salud',
    catWork: 'Trabajo',
    catPersonal: 'Personal',
    catUrgent: 'Urgente',
    catMedicine: 'Medicina',
    catBirthday: 'Cumpleaños',
    repeatNone: 'Sin repetición',
    repeatDaily: 'Cada día',
    repeatEvery: 'Cada...',
    repeatEveryHours: 'Cada (horas)',
    repeatMonthly: 'Cada mes',
    repeatCustom: 'Intervalo personalizado',
    soundBell: 'Campana',
    soundAlarm: 'Alarma',
    soundGentle: 'Suave',
    soundNone: 'Sin sonido',
    weekMon: 'Lun', weekTue: 'Mar', weekWed: 'Mié', weekThu: 'Jue', weekFri: 'Vie', weekSat: 'Sáb', weekSun: 'Dom',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    signInGoogle: 'Iniciar sesión con Google',
    orEmail: 'o con email',
    password: 'Contraseña',
    noAccount: '¿Sin cuenta?',
    haveAccount: '¿Ya tienes cuenta?',
    authSubtitle: 'Inicia sesión para sincronizar tareas',
    authError: 'Error de autenticación',
    checkEmail: 'Revisa tu correo',
    confirmEmailSent: 'Email de confirmación enviado',
    logout: 'Cerrar sesión',
  },
  fr: {
    appName: 'ChimeUp',
    today: 'Aujourd\'hui',
    calendar: 'Calendrier',
    notes: 'Notes',
    settings: 'Paramètres',
    addTask: 'Ajouter une tâche',
    taskName: 'Nom de la tâche',
    taskDescription: 'Description',
    selectDate: 'Date',
    selectTime: 'Heure',
    save: 'Enregistrer',
    cancel: 'Annuler',
    edit: 'Modifier',
    delete: 'Supprimer',
    complete: 'Terminé',
    pending: 'En attente',
    tomorrow: 'Demain',
    timeToComplete: 'C\'est l\'heure !',
    enableNotifications: 'Notifications',
    noTasks: 'Aucune tâche',
    createFirst: 'Ajoutez votre première tâche',
    taskCreated: 'Tâche créée',
    taskUpdated: 'Tâche mise à jour',
    taskDeleted: 'Tâche supprimée',
    taskCompleted: 'Tâche terminée !',
    category: 'Catégorie',
    repeat: 'Répéter',
    sound: 'Son',
    listenSound: 'Écouter',
    snooze5: 'Dans 5 min',
    snooze10: 'Dans 10 min',
    snooze30: 'Dans 30 min',
    snooze60: 'Dans 1 heure',
    snoozeCustom: 'Répéter dans...',
    snoozeCustomPlaceholder: 'Min.',
    history: 'Historique',
    clearHistory: 'Effacer l\'historique',
    autoCleanup: 'Nettoyage auto',
    theme: 'Thème',
    themeLight: 'Clair',
    themeDark: 'Sombre',
    themeAuto: 'Auto',
    language: 'Langue',
    newNote: 'Nouvelle note',
    deleteNote: 'Supprimer la note',
    writeHere: 'Commencez à écrire...',
    medicine: 'Médicament',
    medicineName: 'Nom du médicament',
    medicineTime: 'Heure de prise',
    medicineTaken: 'Pris',
    medicineHistory: 'Historique des prises',
    voiceInput: 'Saisie vocale',
    noTasksToday: 'Pas de tâches pour aujourd\'hui',
    enjoyDay: 'Détendez-vous ! 🎉',
    overdue: 'En retard',
    upcoming: 'À venir',
    allTasks: 'Toutes les tâches',
    days7: '7 jours',
    days30: '30 jours',
    days90: '90 jours',
    repeatInterval: 'Intervalle (heures)',
    notifEnabled: '✅ Activées',
    notifDisabled: '❌ Désactivées',
    notifGranted: '✅ Activées',
    notifDenied: '❌ Refusées par le navigateur',
    notifUnsupported: '❌ Le navigateur ne supporte pas les notifications',
    historyEmpty: '🎉 Vide',
    listening: 'Écoute...',
    aiProcessing: 'AI traite...',
    voiceConfirmText: 'Vérifiez et confirmez le texte :',
    confirm: 'Confirmer',
    selectDatePicker: 'Choisir une date',
    customRemindersHint: '📅 Indiquez les dates et heures des rappels :',
    fillHighlightedFields: '⚠️ Remplissez les champs surlignés :',
    fieldDate: 'Date',
    fieldTime: 'Heure',
    fieldName: 'Nom',
    addReminder: '+ Ajouter un rappel',
    reminder: '⏰ Rappel',
    dismiss: 'Ignorer',
    remindIn10: '⏰ Rappeler dans 10 min',
    remindIn30: '⏰ Rappeler dans 30 min',
    remindIn1h: '⏰ Rappeler dans 1 heure',
    remindAt: 'Rappeler...',
    setReminder: 'Définir un rappel',
    chatSaved: '💬 Chat sauvegardé',
    aiChatTitle: 'Chat AI',
    chatHistory: 'Historique des chats',
    chatPlaceholder: 'Écrivez un message...',
    saveAll: 'Tout sauvegarder',
    saveSelected: 'Sauvegarder la sélection',
    selectMessages: 'Sélectionner',
    chatEmpty: 'Commencez une conversation avec l\'assistant AI',
    newChat: 'Nouveau chat',
    noHistoryChats: 'Aucun chat sauvegardé',
    clearAll: 'Tout effacer',
    clearChat: 'Effacer le chat',
    tasks: 'tâches',
    speechUnsupported: 'Le navigateur ne supporte pas la reconnaissance vocale',
    catHealth: 'Santé',
    catWork: 'Travail',
    catPersonal: 'Personnel',
    catUrgent: 'Urgent',
    catMedicine: 'Médicament',
    catBirthday: 'Anniversaire',
    repeatNone: 'Pas de répétition',
    repeatDaily: 'Chaque jour',
    repeatEvery: 'Chaque...',
    repeatEveryHours: 'Chaque (heures)',
    repeatMonthly: 'Chaque mois',
    repeatCustom: 'Intervalle personnalisé',
    soundBell: 'Cloche',
    soundAlarm: 'Alarme',
    soundGentle: 'Doux',
    soundNone: 'Silencieux',
    weekMon: 'Lun', weekTue: 'Mar', weekWed: 'Mer', weekThu: 'Jeu', weekFri: 'Ven', weekSat: 'Sam', weekSun: 'Dim',
    signIn: 'Se connecter',
    signUp: 'S\'inscrire',
    signInGoogle: 'Se connecter avec Google',
    orEmail: 'ou par email',
    password: 'Mot de passe',
    noAccount: 'Pas de compte ?',
    haveAccount: 'Déjà un compte ?',
    authSubtitle: 'Connectez-vous pour synchroniser les tâches',
    authError: 'Erreur d\'authentification',
    checkEmail: 'Vérifiez votre email',
    confirmEmailSent: 'Email de confirmation envoyé',
    logout: 'Se déconnecter',
  },
  de: {
    appName: 'ChimeUp',
    today: 'Heute',
    calendar: 'Kalender',
    notes: 'Notizen',
    settings: 'Einstellungen',
    addTask: 'Aufgabe hinzufügen',
    taskName: 'Aufgabenname',
    taskDescription: 'Beschreibung',
    selectDate: 'Datum',
    selectTime: 'Zeit',
    save: 'Speichern',
    cancel: 'Abbrechen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    complete: 'Erledigt',
    pending: 'Ausstehend',
    tomorrow: 'Morgen',
    timeToComplete: 'Zeit zum Erledigen!',
    enableNotifications: 'Benachrichtigungen',
    noTasks: 'Keine Aufgaben',
    createFirst: 'Erstelle deine erste Aufgabe',
    taskCreated: 'Aufgabe erstellt',
    taskUpdated: 'Aufgabe aktualisiert',
    taskDeleted: 'Aufgabe gelöscht',
    taskCompleted: 'Aufgabe erledigt!',
    category: 'Kategorie',
    repeat: 'Wiederholen',
    sound: 'Ton',
    listenSound: 'Anhören',
    snooze5: 'In 5 Min',
    snooze10: 'In 10 Min',
    snooze30: 'In 30 Min',
    snooze60: 'In 1 Std',
    snoozeCustom: 'Wiederholen in...',
    snoozeCustomPlaceholder: 'Min.',
    history: 'Verlauf',
    clearHistory: 'Verlauf löschen',
    autoCleanup: 'Auto-Bereinigung',
    theme: 'Design',
    themeLight: 'Hell',
    themeDark: 'Dunkel',
    themeAuto: 'Auto',
    language: 'Sprache',
    newNote: 'Neue Notiz',
    deleteNote: 'Notiz löschen',
    writeHere: 'Schreibe hier...',
    medicine: 'Medizin',
    medicineName: 'Medikamentenname',
    medicineTime: 'Einnahmezeit',
    medicineTaken: 'Eingenommen',
    medicineHistory: 'Einnahmeverlauf',
    voiceInput: 'Spracheingabe',
    noTasksToday: 'Keine Aufgaben für heute',
    enjoyDay: 'Zeit zum Entspannen! 🎉',
    overdue: 'Überfällig',
    upcoming: 'Anstehend',
    allTasks: 'Alle Aufgaben',
    days7: '7 Tage',
    days30: '30 Tage',
    days90: '90 Tage',
    repeatInterval: 'Intervall (Stunden)',
    notifEnabled: '✅ Aktiviert',
    notifDisabled: '❌ Deaktiviert',
    notifGranted: '✅ Aktiviert',
    notifDenied: '❌ Vom Browser abgelehnt',
    notifUnsupported: '❌ Browser unterstützt keine Benachrichtigungen',
    historyEmpty: '🎉 Leer',
    listening: 'Höre zu...',
    aiProcessing: 'AI verarbeitet...',
    voiceConfirmText: 'Text prüfen und bestätigen:',
    confirm: 'Bestätigen',
    selectDatePicker: 'Datum wählen',
    customRemindersHint: '📅 Daten und Zeiten für Erinnerungen angeben:',
    fillHighlightedFields: '⚠️ Markierte Felder ausfüllen:',
    fieldDate: 'Datum',
    fieldTime: 'Zeit',
    fieldName: 'Name',
    addReminder: '+ Erinnerung hinzufügen',
    reminder: '⏰ Erinnerung',
    dismiss: 'Verwerfen',
    remindIn10: '⏰ In 10 Min erinnern',
    remindIn30: '⏰ In 30 Min erinnern',
    remindIn1h: '⏰ In 1 Std erinnern',
    remindAt: 'Erinnern...',
    setReminder: 'Erinnerung setzen',
    chatSaved: '💬 Chat gespeichert',
    aiChatTitle: 'AI Chat',
    chatHistory: 'Chatverlauf',
    chatPlaceholder: 'Nachricht schreiben...',
    saveAll: 'Alles speichern',
    saveSelected: 'Auswahl speichern',
    selectMessages: 'Auswählen',
    chatEmpty: 'Starte ein Gespräch mit dem AI-Assistenten',
    newChat: 'Neuer Chat',
    noHistoryChats: 'Keine gespeicherten Chats',
    clearAll: 'Alles löschen',
    clearChat: 'Chat löschen',
    tasks: 'Aufgaben',
    speechUnsupported: 'Browser unterstützt keine Spracherkennung',
    catHealth: 'Gesundheit',
    catWork: 'Arbeit',
    catPersonal: 'Persönlich',
    catUrgent: 'Dringend',
    catMedicine: 'Medizin',
    catBirthday: 'Geburtstag',
    repeatNone: 'Keine Wiederholung',
    repeatDaily: 'Täglich',
    repeatEvery: 'Alle...',
    repeatEveryHours: 'Alle (Stunden)',
    repeatMonthly: 'Monatlich',
    repeatCustom: 'Benutzerdefiniert',
    soundBell: 'Glocke',
    soundAlarm: 'Wecker',
    soundGentle: 'Sanft',
    soundNone: 'Stumm',
    weekMon: 'Mo', weekTue: 'Di', weekWed: 'Mi', weekThu: 'Do', weekFri: 'Fr', weekSat: 'Sa', weekSun: 'So',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    signInGoogle: 'Mit Google anmelden',
    orEmail: 'oder per E-Mail',
    password: 'Passwort',
    noAccount: 'Kein Konto?',
    haveAccount: 'Bereits ein Konto?',
    authSubtitle: 'Melden Sie sich an, um Aufgaben zu synchronisieren',
    authError: 'Authentifizierungsfehler',
    checkEmail: 'E-Mail prüfen',
    confirmEmailSent: 'Bestätigungsmail gesendet',
    logout: 'Abmelden',
  },
  zh: {
    appName: 'ChimeUp',
    today: '今天',
    calendar: '日历',
    notes: '笔记',
    settings: '设置',
    addTask: '添加任务',
    taskName: '任务名称',
    taskDescription: '描述',
    selectDate: '日期',
    selectTime: '时间',
    save: '保存',
    cancel: '取消',
    edit: '编辑',
    delete: '删除',
    complete: '完成',
    pending: '待办',
    tomorrow: '明天',
    timeToComplete: '该完成了！',
    enableNotifications: '通知',
    noTasks: '没有任务',
    createFirst: '添加你的第一个任务',
    taskCreated: '任务已创建',
    taskUpdated: '任务已更新',
    taskDeleted: '任务已删除',
    taskCompleted: '任务已完成！',
    category: '分类',
    repeat: '重复',
    sound: '声音',
    listenSound: '试听',
    snooze5: '5分钟后',
    snooze10: '10分钟后',
    snooze30: '30分钟后',
    snooze60: '1小时后',
    snoozeCustom: '稍后提醒...',
    snoozeCustomPlaceholder: '分钟',
    history: '历史',
    clearHistory: '清除历史',
    autoCleanup: '自动清理',
    theme: '主题',
    themeLight: '浅色',
    themeDark: '深色',
    themeAuto: '自动',
    language: '语言',
    newNote: '新笔记',
    deleteNote: '删除笔记',
    writeHere: '开始写...',
    medicine: '药物',
    medicineName: '药物名称',
    medicineTime: '服用时间',
    medicineTaken: '已服',
    medicineHistory: '用药记录',
    voiceInput: '语音输入',
    noTasksToday: '今天没有任务',
    enjoyDay: '放松一下！ 🎉',
    overdue: '已逾期',
    upcoming: '即将到来',
    allTasks: '所有任务',
    days7: '7天',
    days30: '30天',
    days90: '90天',
    repeatInterval: '间隔 (小时)',
    notifEnabled: '✅ 已启用',
    notifDisabled: '❌ 已禁用',
    notifGranted: '✅ 已启用',
    notifDenied: '❌ 被浏览器拒绝',
    notifUnsupported: '❌ 浏览器不支持通知',
    historyEmpty: '🎉 空',
    listening: '正在听...',
    aiProcessing: 'AI处理中...',
    voiceConfirmText: '检查并确认文本：',
    confirm: '确认',
    selectDatePicker: '选择日期',
    customRemindersHint: '📅 设置提醒的日期和时间：',
    fillHighlightedFields: '⚠️ 填写标记的字段：',
    fieldDate: '日期',
    fieldTime: '时间',
    fieldName: '名称',
    addReminder: '+ 添加提醒',
    reminder: '⏰ 提醒',
    dismiss: '忽略',
    remindIn10: '⏰ 10分钟后提醒',
    remindIn30: '⏰ 30分钟后提醒',
    remindIn1h: '⏰ 1小时后提醒',
    remindAt: '提醒...',
    setReminder: '设置提醒',
    chatSaved: '💬 聊天已保存',
    aiChatTitle: 'AI聊天',
    chatHistory: '聊天记录',
    chatPlaceholder: '输入消息...',
    saveAll: '全部保存',
    saveSelected: '保存选中',
    selectMessages: '选择',
    chatEmpty: '开始与AI助手对话',
    newChat: '新聊天',
    noHistoryChats: '没有保存的聊天',
    clearAll: '全部清除',
    clearChat: '清除聊天',
    tasks: '任务',
    speechUnsupported: '浏览器不支持语音识别',
    catHealth: '健康',
    catWork: '工作',
    catPersonal: '个人',
    catUrgent: '紧急',
    catMedicine: '药物',
    catBirthday: '生日',
    repeatNone: '不重复',
    repeatDaily: '每天',
    repeatEvery: '每...',
    repeatEveryHours: '每 (小时)',
    repeatMonthly: '每月',
    repeatCustom: '自定义间隔',
    soundBell: '铃声',
    soundAlarm: '闹钟',
    soundGentle: '轻柔',
    soundNone: '静音',
    weekMon: '一', weekTue: '二', weekWed: '三', weekThu: '四', weekFri: '五', weekSat: '六', weekSun: '日',
    signIn: '登录',
    signUp: '注册',
    signInGoogle: '使用Google登录',
    orEmail: '或使用邮箱',
    password: '密码',
    noAccount: '没有账户？',
    haveAccount: '已有账户？',
    authSubtitle: '登录以同步任务',
    authError: '认证错误',
    checkEmail: '检查邮箱',
    confirmEmailSent: '确认邮件已发送',
    logout: '退出登录',
  },
  ja: {
    appName: 'ChimeUp',
    today: '今日',
    calendar: 'カレンダー',
    notes: 'メモ',
    settings: '設定',
    addTask: 'タスクを追加',
    taskName: 'タスク名',
    taskDescription: '説明',
    selectDate: '日付',
    selectTime: '時間',
    save: '保存',
    cancel: 'キャンセル',
    edit: '編集',
    delete: '削除',
    complete: '完了',
    pending: '保留',
    tomorrow: '明日',
    timeToComplete: '完了の時間です！',
    enableNotifications: '通知',
    noTasks: 'タスクなし',
    createFirst: '最初のタスクを追加',
    taskCreated: 'タスクを作成しました',
    taskUpdated: 'タスクを更新しました',
    taskDeleted: 'タスクを削除しました',
    taskCompleted: 'タスク完了！',
    category: 'カテゴリー',
    repeat: '繰り返し',
    sound: 'サウンド',
    listenSound: '視聴',
    snooze5: '5分後',
    snooze10: '10分後',
    snooze30: '30分後',
    snooze60: '1時間後',
    snoozeCustom: '後で通知...',
    snoozeCustomPlaceholder: '分',
    history: '履歴',
    clearHistory: '履歴をクリア',
    autoCleanup: '自動クリーンアップ',
    theme: 'テーマ',
    themeLight: 'ライト',
    themeDark: 'ダーク',
    themeAuto: '自動',
    language: '言語',
    newNote: '新しいメモ',
    deleteNote: 'メモを削除',
    writeHere: '入力を開始...',
    medicine: '薬',
    medicineName: '薬の名前',
    medicineTime: '服用時間',
    medicineTaken: '服用済み',
    medicineHistory: '服用履歴',
    voiceInput: '音声入力',
    noTasksToday: '今日のタスクはありません',
    enjoyDay: 'リラックスしましょう！ 🎉',
    overdue: '期限切れ',
    upcoming: '予定',
    allTasks: 'すべてのタスク',
    days7: '7日',
    days30: '30日',
    days90: '90日',
    repeatInterval: '間隔（時間）',
    notifEnabled: '✅ 有効',
    notifDisabled: '❌ 無効',
    notifGranted: '✅ 有効',
    notifDenied: '❌ ブラウザにより拒否',
    notifUnsupported: '❌ ブラウザは通知をサポートしていません',
    historyEmpty: '🎉 空です',
    listening: '聞いています...',
    aiProcessing: 'AI処理中...',
    voiceConfirmText: 'テキストを確認して承認：',
    confirm: '確認',
    selectDatePicker: '日付を選択',
    customRemindersHint: '📅 リマインダーの日時を設定：',
    fillHighlightedFields: '⚠️ ハイライトされたフィールドを入力：',
    fieldDate: '日付',
    fieldTime: '時間',
    fieldName: '名前',
    addReminder: '+ リマインダーを追加',
    reminder: '⏰ リマインダー',
    dismiss: '無視',
    remindIn10: '⏰ 10分後にリマインド',
    remindIn30: '⏰ 30分後にリマインド',
    remindIn1h: '⏰ 1時間後にリマインド',
    remindAt: 'リマインド...',
    setReminder: 'リマインダーを設定',
    chatSaved: '💬 チャットを保存しました',
    aiChatTitle: 'AIチャット',
    chatHistory: 'チャット履歴',
    chatPlaceholder: 'メッセージを入力...',
    saveAll: 'すべて保存',
    saveSelected: '選択を保存',
    selectMessages: '選択',
    chatEmpty: 'AIアシスタントとの会話を開始',
    newChat: '新しいチャット',
    noHistoryChats: '保存されたチャットはありません',
    clearAll: 'すべてクリア',
    clearChat: 'チャットをクリア',
    tasks: 'タスク',
    speechUnsupported: 'ブラウザは音声認識をサポートしていません',
    catHealth: '健康',
    catWork: '仕事',
    catPersonal: '個人',
    catUrgent: '緊急',
    catMedicine: '薬',
    catBirthday: '誕生日',
    repeatNone: '繰り返しなし',
    repeatDaily: '毎日',
    repeatEvery: '毎...',
    repeatEveryHours: '毎 (時間)',
    repeatMonthly: '毎月',
    repeatCustom: 'カスタム間隔',
    soundBell: 'ベル',
    soundAlarm: 'アラーム',
    soundGentle: '穏やか',
    soundNone: '無音',
    weekMon: '月', weekTue: '火', weekWed: '水', weekThu: '木', weekFri: '金', weekSat: '土', weekSun: '日',
    signIn: 'ログイン',
    signUp: 'サインアップ',
    signInGoogle: 'Googleでログイン',
    orEmail: 'またはメールで',
    password: 'パスワード',
    noAccount: 'アカウントがない？',
    haveAccount: 'アカウントをお持ちですか？',
    authSubtitle: 'ログインして同期',
    authError: '認証エラー',
    checkEmail: 'メールを確認',
    confirmEmailSent: '確認メールを送信しました',
    logout: 'ログアウト',
  },
  ar: {
    appName: 'ChimeUp',
    today: 'اليوم',
    calendar: 'التقويم',
    notes: 'الملاحظات',
    settings: 'الإعدادات',
    addTask: 'إضافة مهمة',
    taskName: 'اسم المهمة',
    taskDescription: 'الوصف',
    selectDate: 'التاريخ',
    selectTime: 'الوقت',
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    complete: 'تم',
    pending: 'قيد الانتظار',
    tomorrow: 'غداً',
    timeToComplete: 'حان وقت الإنجاز!',
    enableNotifications: 'الإشعارات',
    noTasks: 'لا توجد مهام',
    createFirst: 'أضف مهمتك الأولى',
    taskCreated: 'تم إنشاء المهمة',
    taskUpdated: 'تم تحديث المهمة',
    taskDeleted: 'تم حذف المهمة',
    taskCompleted: 'اكتملت المهمة!',
    category: 'الفئة',
    repeat: 'تكرار',
    sound: 'صوت',
    listenSound: 'استماع',
    snooze5: 'بعد 5 دقائق',
    snooze10: 'بعد 10 دقائق',
    snooze30: 'بعد 30 دقيقة',
    snooze60: 'بعد ساعة',
    snoozeCustom: 'تكرار في...',
    snoozeCustomPlaceholder: 'دقيقة',
    history: 'السجل',
    clearHistory: 'مسح السجل',
    autoCleanup: 'تنظيف تلقائي',
    theme: 'المظهر',
    themeLight: 'فاتح',
    themeDark: 'داكن',
    themeAuto: 'تلقائي',
    language: 'اللغة',
    newNote: 'ملاحظة جديدة',
    deleteNote: 'حذف الملاحظة',
    writeHere: 'ابدأ الكتابة...',
    medicine: 'الدواء',
    medicineName: 'اسم الدواء',
    medicineTime: 'وقت الجرعة',
    medicineTaken: 'تم تناوله',
    medicineHistory: 'سجل الأدوية',
    voiceInput: 'إدخال صوتي',
    noTasksToday: 'لا توجد مهام لليوم',
    enjoyDay: 'وقت الاسترخاء! 🎉',
    overdue: 'متأخر',
    upcoming: 'القادمة',
    allTasks: 'كل المهام',
    days7: '7 أيام',
    days30: '30 يوماً',
    days90: '90 يوماً',
    repeatInterval: 'الفترة (ساعات)',
    notifEnabled: '✅ مفعّلة',
    notifDisabled: '❌ معطّلة',
    notifGranted: '✅ مفعّلة',
    notifDenied: '❌ رفضها المتصفح',
    notifUnsupported: '❌ المتصفح لا يدعم الإشعارات',
    historyEmpty: '🎉 فارغ',
    listening: 'أستمع...',
    aiProcessing: 'AI يعالج...',
    voiceConfirmText: 'تحقق وأكّد النص:',
    confirm: 'تأكيد',
    selectDatePicker: 'اختر تاريخاً',
    customRemindersHint: '📅 حدد تواريخ وأوقات التذكيرات:',
    fillHighlightedFields: '⚠️ أكمل الحقول المحددة:',
    fieldDate: 'التاريخ',
    fieldTime: 'الوقت',
    fieldName: 'الاسم',
    addReminder: '+ إضافة تذكير',
    reminder: '⏰ تذكير',
    dismiss: 'رفض',
    remindIn10: '⏰ تذكير بعد 10 دقائق',
    remindIn30: '⏰ تذكير بعد 30 دقيقة',
    remindIn1h: '⏰ تذكير بعد ساعة',
    remindAt: 'تذكير...',
    setReminder: 'تعيين تذكير',
    chatSaved: '💬 تم حفظ المحادثة',
    aiChatTitle: 'محادثة AI',
    chatHistory: 'سجل المحادثات',
    chatPlaceholder: 'اكتب رسالة...',
    saveAll: 'حفظ الكل',
    saveSelected: 'حفظ المحدد',
    selectMessages: 'تحديد',
    chatEmpty: 'ابدأ محادثة مع مساعد AI',
    newChat: 'محادثة جديدة',
    noHistoryChats: 'لا توجد محادثات محفوظة',
    clearAll: 'مسح الكل',
    clearChat: 'مسح المحادثة',
    tasks: 'مهام',
    speechUnsupported: 'المتصفح لا يدعم التعرف على الكلام',
    catHealth: 'صحة',
    catWork: 'عمل',
    catPersonal: 'شخصي',
    catUrgent: 'عاجل',
    catMedicine: 'دواء',
    catBirthday: 'عيد ميلاد',
    repeatNone: 'بدون تكرار',
    repeatDaily: 'كل يوم',
    repeatEvery: 'كل...',
    repeatEveryHours: 'كل (ساعات)',
    repeatMonthly: 'كل شهر',
    repeatCustom: 'فترة مخصصة',
    soundBell: 'جرس',
    soundAlarm: 'منبه',
    soundGentle: 'ناعم',
    soundNone: 'صامت',
    weekMon: 'إث', weekTue: 'ثل', weekWed: 'أر', weekThu: 'خم', weekFri: 'جم', weekSat: 'سب', weekSun: 'أح',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signInGoogle: 'الدخول عبر Google',
    orEmail: 'أو بالبريد الإلكتروني',
    password: 'كلمة المرور',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب بالفعل؟',
    authSubtitle: 'سجل الدخول لمزامنة المهام',
    authError: 'خطأ في المصادقة',
    checkEmail: 'تحقق من بريدك',
    confirmEmailSent: 'تم إرسال رسالة التأكيد',
    logout: 'تسجيل الخروج',
  },
  pt: {
    appName: 'ChimeUp',
    today: 'Hoje',
    calendar: 'Calendário',
    notes: 'Notas',
    settings: 'Configurações',
    addTask: 'Adicionar tarefa',
    taskName: 'Nome da tarefa',
    taskDescription: 'Descrição',
    selectDate: 'Data',
    selectTime: 'Hora',
    save: 'Salvar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Excluir',
    complete: 'Concluído',
    pending: 'Pendente',
    tomorrow: 'Amanhã',
    timeToComplete: 'Hora de concluir!',
    enableNotifications: 'Notificações',
    noTasks: 'Sem tarefas',
    createFirst: 'Adicione sua primeira tarefa',
    taskCreated: 'Tarefa criada',
    taskUpdated: 'Tarefa atualizada',
    taskDeleted: 'Tarefa excluída',
    taskCompleted: 'Tarefa concluída!',
    category: 'Categoria',
    repeat: 'Repetir',
    sound: 'Som',
    listenSound: 'Ouvir',
    snooze5: 'Em 5 min',
    snooze10: 'Em 10 min',
    snooze30: 'Em 30 min',
    snooze60: 'Em 1 hora',
    snoozeCustom: 'Repetir em...',
    snoozeCustomPlaceholder: 'Min.',
    history: 'Histórico',
    clearHistory: 'Limpar histórico',
    autoCleanup: 'Limpeza automática',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeAuto: 'Automático',
    language: 'Idioma',
    newNote: 'Nova nota',
    deleteNote: 'Excluir nota',
    writeHere: 'Comece a escrever...',
    medicine: 'Remédio',
    medicineName: 'Nome do remédio',
    medicineTime: 'Hora da tomada',
    medicineTaken: 'Tomado',
    medicineHistory: 'Histórico de doses',
    voiceInput: 'Entrada de voz',
    noTasksToday: 'Nenhuma tarefa para hoje',
    enjoyDay: 'Hora de relaxar! 🎉',
    overdue: 'Atrasado',
    upcoming: 'Próximos',
    allTasks: 'Todas as tarefas',
    days7: '7 dias',
    days30: '30 dias',
    days90: '90 dias',
    repeatInterval: 'Intervalo (horas)',
    notifEnabled: '✅ Ativadas',
    notifDisabled: '❌ Desativadas',
    notifGranted: '✅ Ativadas',
    notifDenied: '❌ Negadas pelo navegador',
    notifUnsupported: '❌ Navegador não suporta notificações',
    historyEmpty: '🎉 Vazio',
    listening: 'Ouvindo...',
    aiProcessing: 'AI processando...',
    voiceConfirmText: 'Verifique e confirme o texto:',
    confirm: 'Confirmar',
    selectDatePicker: 'Selecionar data',
    customRemindersHint: '📅 Defina datas e horários dos lembretes:',
    fillHighlightedFields: '⚠️ Preencha os campos destacados:',
    fieldDate: 'Data',
    fieldTime: 'Hora',
    fieldName: 'Nome',
    addReminder: '+ Adicionar lembrete',
    reminder: '⏰ Lembrete',
    dismiss: 'Dispensar',
    remindIn10: '⏰ Lembrar em 10 min',
    remindIn30: '⏰ Lembrar em 30 min',
    remindIn1h: '⏰ Lembrar em 1 hora',
    remindAt: 'Lembrar...',
    setReminder: 'Definir lembrete',
    chatSaved: '💬 Chat salvo',
    aiChatTitle: 'Chat AI',
    chatHistory: 'Histórico de chats',
    chatPlaceholder: 'Digite uma mensagem...',
    saveAll: 'Salvar tudo',
    saveSelected: 'Salvar seleção',
    selectMessages: 'Selecionar',
    chatEmpty: 'Comece uma conversa com o assistente de IA',
    newChat: 'Nova conversa',
    noHistoryChats: 'Nenhuma conversa salva',
    clearAll: 'Limpar tudo',
    clearChat: 'Limpar conversa',
    tasks: 'tarefas',
    speechUnsupported: 'O navegador não suporta reconhecimento de voz',
    catHealth: 'Saúde',
    catWork: 'Trabalho',
    catPersonal: 'Pessoal',
    catUrgent: 'Urgente',
    catMedicine: 'Remédio',
    catBirthday: 'Aniversário',
    repeatNone: 'Sem repetição',
    repeatDaily: 'Diariamente',
    repeatEvery: 'A cada...',
    repeatEveryHours: 'A cada (horas)',
    repeatMonthly: 'Mensalmente',
    repeatCustom: 'Intervalo personalizado',
    soundBell: 'Sino',
    soundAlarm: 'Alarme',
    soundGentle: 'Suave',
    soundNone: 'Silencioso',
    weekMon: 'Seg', weekTue: 'Ter', weekWed: 'Qua', weekThu: 'Qui', weekFri: 'Sex', weekSat: 'Sáb', weekSun: 'Dom',
    signIn: 'Entrar',
    signUp: 'Registrar',
    signInGoogle: 'Entrar com Google',
    orEmail: 'ou por email',
    password: 'Senha',
    noAccount: 'Sem conta?',
    haveAccount: 'Já tem conta?',
    authSubtitle: 'Entre para sincronizar tarefas',
    authError: 'Erro de autenticação',
    checkEmail: 'Verifique seu email',
    confirmEmailSent: 'Email de confirmação enviado',
    logout: 'Sair',
  },
  hi: {
    appName: 'ChimeUp',
    today: 'आज',
    calendar: 'कैलेंडर',
    notes: 'नोट्स',
    settings: 'सेटिंग्स',
    addTask: 'कार्य जोड़ें',
    taskName: 'कार्य का नाम',
    taskDescription: 'विवरण',
    selectDate: 'तारीख',
    selectTime: 'समय',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    complete: 'पूर्ण',
    pending: 'लंबित',
    tomorrow: 'कल',
    timeToComplete: 'पूरा करने का समय!',
    enableNotifications: 'सूचनाएं',
    noTasks: 'कोई कार्य नहीं',
    createFirst: 'अपना पहला कार्य जोड़ें',
    taskCreated: 'कार्य बनाया गया',
    taskUpdated: 'कार्य अपडेट किया गया',
    taskDeleted: 'कार्य हटा दिया गया',
    taskCompleted: 'कार्य पूरा हुआ!',
    category: 'श्रेणी',
    repeat: 'दोहराएं',
    sound: 'ध्वनि',
    listenSound: 'सुनें',
    snooze5: '5 मिनट में',
    snooze10: '10 मिनट में',
    snooze30: '30 मिनट में',
    snooze60: '1 घंटे में',
    snoozeCustom: 'कस्टम अंतराल...',
    snoozeCustomPlaceholder: 'मिनट',
    history: 'इतिहास',
    clearHistory: 'इतिहास साफ़ करें',
    autoCleanup: 'स्वचालित सफाई',
    theme: 'थीम',
    themeLight: 'हल्का',
    themeDark: 'गहरा',
    themeAuto: 'ऑटो',
    language: 'भाषा',
    newNote: 'नया नोट',
    deleteNote: 'नोट हटाएं',
    writeHere: 'लिखना शुरू करें...',
    medicine: 'दवा',
    medicineName: 'दवा का नाम',
    medicineTime: 'दवा का समय',
    medicineTaken: 'लिया गया',
    medicineHistory: 'दवा का इतिहास',
    voiceInput: 'वॉयस इनपुट',
    noTasksToday: 'आज के लिए कोई कार्य नहीं',
    enjoyDay: 'आराम करने का समय! 🎉',
    overdue: 'देरी से',
    upcoming: 'आगामी',
    allTasks: 'सभी कार्य',
    days7: '7 दिन',
    days30: '30 दिन',
    days90: '90 दिन',
    repeatInterval: 'अंतराल (घंटे)',
    notifEnabled: '✅ सक्रिय',
    notifDisabled: '❌ निष्क्रिय',
    notifGranted: '✅ सक्रिय',
    notifDenied: '❌ ब्राउज़र ने अस्वीकार किया',
    notifUnsupported: '❌ ब्राउज़र सूचनाओं का समर्थन नहीं करता',
    historyEmpty: '🎉 खाली',
    listening: 'सुन रहा हूं...',
    aiProcessing: 'AI प्रक्रिया कर रहा है...',
    voiceConfirmText: 'पाठ जांचें और पुष्टि करें:',
    confirm: 'पुष्टि करें',
    selectDatePicker: 'तारीख चुनें',
    customRemindersHint: '📅 रिमाइंडर की तारीख और समय सेट करें:',
    fillHighlightedFields: '⚠️ हाइलाइट किए गए फ़ील्ड भरें:',
    fieldDate: 'तारीख',
    fieldTime: 'समय',
    fieldName: 'नाम',
    addReminder: '+ रिमाइंडर जोड़ें',
    reminder: '⏰ रिमाइंडर',
    dismiss: 'खारिज करें',
    remindIn10: '⏰ 10 मिनट में याद दिलाएं',
    remindIn30: '⏰ 30 मिनट में याद दिलाएं',
    remindIn1h: '⏰ 1 घंटे में याद दिलाएं',
    remindAt: 'याद दिलाएं...',
    setReminder: 'रिमाइंडर सेट करें',
    chatSaved: '💬 चैट सहेजा गया',
    aiChatTitle: 'AI चैट',
    chatHistory: 'चैट इतिहास',
    chatPlaceholder: 'संदेश लिखें...',
    saveAll: 'सब सहेजें',
    saveSelected: 'चयनित सहेजें',
    selectMessages: 'चुनें',
    chatEmpty: 'AI सहायक के साथ बातचीत शुरू करें',
    newChat: 'नई बातचीत',
    noHistoryChats: 'कोई सहेजी गई बातचीत नहीं',
    clearAll: 'सभी साफ़ करें',
    clearChat: 'बातचीत साफ़ करें',
    tasks: 'कार्य',
    speechUnsupported: 'ब्राउज़र भाषण पहचान का समर्थन नहीं करता है',
    catHealth: 'स्वास्थ्य',
    catWork: 'काम',
    catPersonal: 'व्यक्तिगत',
    catUrgent: 'अत्यावश्यक',
    catMedicine: 'दवा',
    catBirthday: 'जन्मदिन',
    repeatNone: 'कोई दोहराव नहीं',
    repeatDaily: 'प्रतिदिन',
    repeatEvery: 'हर...',
    repeatEveryHours: 'हर (घंटे)',
    repeatMonthly: 'हर महीने',
    repeatCustom: 'कस्टम अंतराल',
    soundBell: 'घंटी',
    soundAlarm: 'अलार्म',
    soundGentle: 'मधुर',
    soundNone: 'मूक',
    weekMon: 'सोम', weekTue: 'मंग', weekWed: 'बुध', weekThu: 'गुरु', weekFri: 'शुक्र', weekSat: 'शनि', weekSun: 'रवि',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    signInGoogle: 'Google से साइन इन करें',
    orEmail: 'या ईमेल के साथ',
    password: 'पासवर्ड',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से ही एक खाता है?',
    authSubtitle: 'कार्यों को सिंक करने के लिए साइन इन करें',
    authError: 'प्रमाणीकरण त्रुटि',
    checkEmail: 'अपना ईमेल जांचें',
    confirmEmailSent: 'पुष्टि ईमेल भेजा गया',
    logout: 'लॉग आउट',
  }
};

export type TranslationKey = keyof typeof translations.ru;

export const useLanguage = () => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('app_language') as Language) || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const t = (key: TranslationKey) => {
    return translations[language][key] || key;
  };

  return { language, setLanguage, t };
};
